//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inchoqate.GUI.Model.Graphics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shaders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shaders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inchoqate.GUI.Model.Graphics.Shaders", typeof(Shaders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///
        ///out vec4 outputColor;
        ///
        ///in vec2 texCoord;
        ///
        ///uniform sampler2D texture0;
        ///
        ///void main()
        ///{
        ///    outputColor = texture(texture0, texCoord);
        ///}.
        /// </summary>
        internal static string BaseFrag {
            get {
                return ResourceManager.GetString("BaseFrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///
        ///layout(location = 0) in vec3 aPosition;
        ///layout(location = 1) in vec2 aTexCoord;
        ///
        ///out vec2 texCoord;
        ///
        ///void main(void)
        ///{
        ///    texCoord = aTexCoord;
        ///
        ///    gl_Position = vec4(aPosition, 1.0);
        ///}.
        /// </summary>
        internal static string BaseVert {
            get {
                return ResourceManager.GetString("BaseVert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///
        ///out vec4 outputColor;
        ///
        ///in vec2 texCoord;
        ///
        ///uniform sampler2D texture0;
        ///uniform float _intensity;
        ///uniform vec3 _weights;
        ///
        ///void main()
        ///{
        ///    vec4 color = texture(texture0, texCoord);
        ///    float gray = dot(color.rgb, _weights);
        ///    vec3 gray3 = vec3(gray);
        ///    vec3 finalColor = mix(color.rgb, gray3, _intensity);
        ///    outputColor = vec4(finalColor, color.a);
        ///}.
        /// </summary>
        internal static string Grayscale {
            get {
                return ResourceManager.GetString("Grayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///
        ///out vec4 outputColor;
        ///
        ///in vec2 texCoord;
        ///
        ///uniform sampler2D texture0;
        ///
        ///void main()
        ///{
        ///    vec4 color = texture(texture0, texCoord);
        ///    outputColor = vec4(color.x, 0.0, color.zw);
        ///}.
        /// </summary>
        internal static string NoGreen {
            get {
                return ResourceManager.GetString("NoGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///
        ///out vec4 outputColor;
        ///
        ///in vec2 texCoord;
        ///
        ///uniform sampler2D texture0;
        ///
        ///void main()
        ///{
        ///    vec4 color = texture(texture0, texCoord);
        ///    outputColor = vec4(0.0, color.yzw);
        ///}.
        /// </summary>
        internal static string NoRed {
            get {
                return ResourceManager.GetString("NoRed", resourceCulture);
            }
        }
    }
}
